language: scala
jdk:
- oraclejdk7
cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.m2
install:
- git clone https://omnia-bamboo:$OMNIA_CI_PASSWORD@github.com/CommBank/ci.git
- chmod ugo+x ci/*
- ci/sbt-setup.sh
script:
- sbt -Dsbt.global.base=$TRAVIS_BUILD_DIR/ci '; test; package'
- ci/sbt-deploy-to.sh libs-releases-local
env:
  global:
  - secure: qwGUECzK7WgI/nqCSq1h3khXEveKgTztDKZjz7gBRW0VsOCmp+w9v+q1jjVFsT96lmQh3JKFDyxbcJO4u6zAW+Zg6GlkEkagC03Se2myXCTafeiVPP0eo/FYUXVl8P8Gwflg8be3CYyOcuf7I2r3Lx8Xy11UyY8M+dqD4OEOix8=
  - secure: KOrZ5oj1qaylY3TrMmKObIJ7GHfUiuVj/+AtXtV1tUEQN55agRuNvtiUY2cQSfXXrCkZIp6JOf+C+wea4FLk3Tqoy4LWG83tTnS1Ok9sxu/PpwxVxclR69+KaN0yXD5jtyv6jigEe9XrfhVsS1ec+IyzPNSv6LTebb4wGVh0KF8=

after_script:
- rm -rf ci
# notifications:
#   webhooks:
#     urls:
#     - https://webhooks.gitter.im/e/???
#     on_success: always
#     on_failure: always
#     on_start: false
